spring.application.name=quizapp

#MySQL DB Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/quiz_app
spring.datasource.username=root
spring.datasource.password=Ruchi@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Dialect (optional in newer versions)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
